[project]
name = 'Blockchain-Based-Marine-Technology-Deep-Ocean-Exploration'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.data-sharing-framework]
path = 'contracts/data-sharing-framework.clar'
clarity_version = 2
epoch = 2.5

[contracts.discovery-documentation]
path = 'contracts/discovery-documentation.clar'
clarity_version = 2
epoch = 2.5

[contracts.environmental-protection]
path = 'contracts/environmental-protection.clar'
clarity_version = 2
epoch = 2.5

[contracts.exploration-protocol]
path = 'contracts/exploration-protocol.clar'
clarity_version = 2
epoch = 2.5

[contracts.research-vessel-verification]
path = 'contracts/research-vessel-verification.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
